/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package irrgarten.UI;

import irrgarten.Directions;
import irrgarten.GameState;

/**
 *
 * @author nekok
 */
public class GraphicUI extends javax.swing.JFrame implements UI {

    private Cursors cursors;
    
    /**
     * Creates new form GraphicUI
     */
    public GraphicUI() {
        initComponents();
        
        setVisible(true); //añadido 
        cursors = new Cursors(this,true); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        laberinto = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        players = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        monsters = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        log = new javax.swing.JTextArea();
        actual = new javax.swing.JLabel();
        ganador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        laberinto.setColumns(20);
        laberinto.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        laberinto.setRows(5);
        jScrollPane1.setViewportView(laberinto);

        players.setColumns(20);
        players.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        players.setRows(5);
        jScrollPane2.setViewportView(players);

        monsters.setColumns(20);
        monsters.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        monsters.setRows(5);
        jScrollPane3.setViewportView(monsters);

        log.setColumns(20);
        log.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        log.setRows(5);
        jScrollPane4.setViewportView(log);

        actual.setFont(new java.awt.Font("Liberation Serif", 0, 24)); // NOI18N
        actual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        actual.setText("actual");
        actual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        ganador.setFont(new java.awt.Font("Liberation Serif", 0, 24)); // NOI18N
        ganador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ganador.setText("ganador");
        ganador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                        .addComponent(actual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ganador, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(actual, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ganador, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //main borrado
    }
    
    
    public void showGame(GameState gameState) {  

        
        this.laberinto.setText(gameState.getLabyrinth().toString());
        this.monsters.setText(gameState.getMonsters().toString());
        this.players.setText(gameState.getPlayers().toString());
        this.log.setText(gameState.getLog());
        
        this.actual.setText("Jugador actual: " + gameState.getCurrentPlayer());
        this.ganador.setText("¿Ganador?: " + gameState.getWinner());

        repaint();
    }
    
    @Override
    public Directions nextMove() {
        return cursors.getDirection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actual;
    private javax.swing.JLabel ganador;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea laberinto;
    private javax.swing.JTextArea log;
    private javax.swing.JTextArea monsters;
    private javax.swing.JTextArea players;
    // End of variables declaration//GEN-END:variables
}
